spring.application.name=kaizen_api
server.port=8080
server.servlet.context-path=/api/v1

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
app.jwt.expiration=3600000
app.jwt.refresh-expiration=604800000